---
apiVersion: v1
kind: Service
metadata:
  name: spc-service
  labels:
    app: spring-petclinic
spec:
  name: spring-petclinic
  type: LoadBalancer
  ports:
  - port: 8080
---
apiVersion: v1
kind: Deployment
metadata:
  name: spc-deployment
  labels:
    app: spring-petclinic
  namespace: dev
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      name: spring-petclinic
      labels:
        app: spring-petclinic
    spec:
      containers:
        - image: optimussurya/project_repo/spring-petclinic
          name: spring-petclinic
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
