---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  name: 
  type: 
  ports:
  - port: 8080
---
apiVersion: v1
kind: Deployment
metadata:
  name: spc
  labels:
    app: spring
  namespace: dev
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: spring
  template:
    metadata:
      name: spring
      labels:
        app: spring
    spec:
      containers:
        - image: optimussurya/project_repo/spring-petclinic
          name: spring-petclinic
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
